name: whatsapp_messenger
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  go_router: ^6.0.4
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  firebase_core: ^2.7.0
  riverpod_annotation:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  device_preview: ^1.1.0
  flutter_native_splash: ^2.2.17
  shared_preferences: ^2.0.17
  flutter_spinkit:
  firebase_storage: ^11.0.14
  firebase_auth: ^4.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner:
  riverpod_generator:
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  mockito: ^5.3.2

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#111B21"
  image: assets/images/splash_light.png
  image_dark: assets/images/splash_dark.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#111B21"
    image: assets/images/splash_light.png
    image_dark: assets/images/splash_dark.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#111B21"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
